spring:
  application:
    name: movie-api
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect:
        format_sql: true
  datasource:
    url:
    username:
    password:

server:
  port:
  error:
    path: /error
    whitelabel:
      enabled: false

jwtSecretKey:
expirationTimeHour:

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
